name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:

    - name: checkout actions
      uses: actions/checkout@v4

    - name: Welcome message
      run: |
        echo "Hello world"
        ls -ltra
        cat README.md